import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import ContextProvider from "@/utils/context/ContextProvider/ContextProvider"
import Logo from "@/components/Logo/Logo";
import Menu from "@/components/Menu/Menu";
import Footer from "@/components/Footer/Footer";
import LoginDialog from "@/components/LoginDialog/LoginDialog";
import ChatDialog from "@/components/ChatDialog/ChatDialog";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${inter.variable}`}>
        <ContextProvider>
          <main>
            <header>
              <Logo></Logo>
              <Menu></Menu>
            </header>
            <section className="content">
            {children}
            </section>
            <LoginDialog></LoginDialog>
            <ChatDialog></ChatDialog>
          </main>
          <Footer></Footer>
        </ContextProvider>
      </body>
    </html>
  );
}
